### PR TITLE
ci: add golangci-lint to test

### PR DESCRIPTION
**Pull request by ccoVeille**
the configuration is very minimal, it would need some configuration.

But it will start reporting issues that should be addressed

### CODE REVIEW

**Comment by ccoVeille** [comment]
I would suggest merging #56, then to merge this even if the test fails

then to try to fix them

**Comment by ccoVeille** [comment]
Install golangci-lint locally theb

simply launch this to report the issue
 
`golangci-lint run`

**Comment by ccoVeille** [comment]
I think about adding new rules and add golangci-lint to the GHA (I thought I did, but apparently I never pushed the changes 🤦)

To validate there is no error added.

What are your thoughts?

I started working on this project since last time we talked.

https://github.com/ccoVeille/golangci-lint-config-examples

**Comment by savedra1** [comment]
Hi @ccoVeille I might need some help understanding this. Would this be a new actions workflow for the project that mandates linting rules etc? I would be happy to use this if so :smile:

**Comment by ccoVeille** [comment]
I opened the following PR, I hope it will be clearer

- #84

**Pull request merged**
